---
title: "Trend visualizations"
output: 
  html_document:
    toc: true
    toc_float: true
date: "`r Sys.Date()`"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      warning = FALSE,
                      message = FALSE,
                      error = TRUE)
```


```{r}
library(dplyr)
library(tidyr)
library(stringr)
library(ggplot2)
library(patchwork)
```

```{r}
region_dictionary <- read.csv(here::here("helper_files",
                                         "region_dictionary.csv"))
```


```{r}
# read in trends
load(here::here("Outputs", 
                "calculated_trends",
                "long-term-trends.RData"))

# read in seasonal amplitudes
load(here::here("Outputs", 
                "calculated_trends", 
                "seasonal_characterization.RData"))

# read in station metadata, including latitude
stn_mdat <- readr::read_csv(here::here("helper_files", "sampling_stations.csv")) |> 
  select(station = "Station Code",
         Latitude,
         Longitude)
```


```{r}
trends_all <- bind_rows(trends_df, trends_met, trends_nut) |> 
  mutate(reserve = str_sub(station, start = 1, end = 3),
         type = case_when(str_ends(station, "wq") ~ "wq",
                          str_ends(station, "met") ~ "met",
                          str_ends(station, "nut") ~ "nut",
                          .default = "something's wrong")) |> 
  left_join(seasonal_by_stn, by = c("station", "parameter")) |>  # join in the seasonal amplitudes
  left_join(region_dictionary, by = c("reserve" = "Reserve")) |>   # join the pre-defined region categories
  left_join(stn_mdat, by = "station")  # join the latitudes


trends_seasonal <- trends_all |> 
  select(station, parameter, reserve, type, Region,
         starts_with("Fall"),
         starts_with("Spring"),
         starts_with("Summer"),
         starts_with("Winter")) |> 
  pivot_longer(c(starts_with("Fall"),
         starts_with("Spring"),
         starts_with("Summer"),
         starts_with("Winter")),
               names_to = c("Season", "parm"),
               names_sep = "_",
               values_to = "value") |> 
  pivot_wider(names_from = parm,
              values_from = value,
              values_fn = mean)  # remove this values_fn line when we know dupes should be gone
```

```{r}
rm(trends_df, trends_met, trends_nut, 
   seasonal_by_stn,
   region_dictionary, stn_mdat)
```


```{r}
trends_all <-  trends_all |> 
  arrange(Region, reserve, station) 

trends_seasonal <- trends_seasonal |> 
  arrange(Region, reserve, station) |> 
  mutate(stn_factor = forcats::fct_inorder(station))

parms <- trends_all |> 
  select(type, parameter) |> 
  distinct() |> 
  arrange(desc(type), parameter) |> 
  pull(parameter)
```


# Long-Term Overall  

## WQ  


```{r, fig.width = 7, fig.height = 7}
trends_all |>
  filter(type == "wq") |> 
  arrange(parameter, Slope, station) |> 
  mutate(stparm = paste0(station, parameter)) |> 
  ggplot(aes(x = forcats::fct_inorder(stparm), y = Slope)) +
  geom_pointrange(aes(ymin = conf.low, ymax = conf.high,
                      col = sig_trend)) +
  geom_hline(yintercept = 0) +
  facet_wrap(~parameter, scales = "free") +
  labs(title = "Slopes for all stations",
       subtitle = "slopes are in [parameter's measurement units] / year",
       x = "Station",
       col = "Significant slope?") +
  theme(axis.text.x = element_blank(), 
        legend.text = element_text(size = 8),
        legend.title = element_text(size = 8),
        legend.position = "bottom", 
        legend.justification = "left",
        legend.direction = "horizontal")
```

```{r, fig.width = 7, fig.height = 7}
ggplot(filter(trends_all, type == "wq")) +
  geom_histogram(aes(x = Slope,
                     fill = parameter),
                 bins = 30,
                 col = "gray20",
                 alpha = 0.8) +
  facet_wrap(~parameter, scales = "free") +
  geom_vline(xintercept = 0,
             linewidth = 1) +
  theme(legend.position = "none") +
  labs(title = "Histograms of slopes for each parameter",
       subtitle = "slopes are in [parameter's measurement units] / year")
```


```{r, fig.width = 7, fig.height = 7}
ggplot(filter(trends_all, type == "wq")) +
  geom_hline(yintercept = 0,
             linewidth = 0.7) +  
  geom_point(aes(x = ts_length,
                 y = Slope,
                 col = parameter),
             alpha = 0.7) +
  geom_smooth(method = "lm", se = TRUE,
              aes(x = ts_length,
                  y = Slope,
                  col = parameter),
              alpha = 0.6) +
  facet_wrap(~parameter, scales = "free") +
  theme(legend.position = "none") +
  labs(title = "Slopes as a function of time series length for each parameter",
       x = "Time Series length (years)",
       subtitle = "slopes are in [parameter's measurement units] / year")
```

```{r, fig.width = 6, fig.height = 3.5}
seas_wq <- trends_all |>
  filter(type == "wq") |> 
  summarize(.by = c(parameter, sig_seasonality),
            n()) |> 
  pivot_wider(names_from = sig_seasonality,
              values_from = `n()`) |> 
  mutate(no = -1*no)

ggplot(seas_wq) +
  geom_segment( aes(x=parameter, xend=parameter, y=no, yend=yes)) +
  geom_point( aes(x=parameter, y=no, color="seasonal"), size=3 ) +
  geom_point( aes(x=parameter, y=yes, color="not seasonal"), size=3 ) +
  geom_hline(yintercept = 0) +
  scale_color_brewer(palette = "Set1") +
  coord_flip()+
  theme(
    legend.position = "none",
  ) +
  xlab("") +
  ylab("# of stations displaying seasonality")
```


## MET  


```{r, fig.width = 7, fig.height = 5}
trends_all |>
  filter(type == "met") |> 
  arrange(parameter, Slope, station) |> 
  mutate(stparm = paste0(station, parameter)) |> 
  ggplot(aes(x = forcats::fct_inorder(stparm), y = Slope)) +
  geom_pointrange(aes(ymin = conf.low, ymax = conf.high,
                      col = sig_trend)) +
  geom_hline(yintercept = 0) +
  facet_wrap(~parameter, scales = "free") +
  labs(title = "Slopes for all stations",
       subtitle = "slopes are in [parameter's measurement units] / year",
       x = "Station",
       col = "Significant slope?") +
  theme(axis.text.x = element_blank(), 
        legend.text = element_text(size = 8),
        legend.title = element_text(size = 8),
        legend.position = "bottom", 
        legend.justification = "left",
        legend.direction = "horizontal")
```

```{r, fig.width = 7, fig.height = 5}
ggplot(filter(trends_all, type == "met")) +
  geom_histogram(aes(x = Slope,
                     fill = parameter),
                 bins = 20,
                 col = "gray20",
                 alpha = 0.8) +
  facet_wrap(~parameter, scales = "free") +
  geom_vline(xintercept = 0,
             linewidth = 1) +
  theme(legend.position = "none") +
  labs(title = "Histograms of slopes for each parameter",
       subtitle = "slopes are in [parameter's measurement units] / year")
```

```{r, fig.width = 7, fig.height = 5}
ggplot(filter(trends_all, type == "met")) +
  geom_hline(yintercept = 0,
             linewidth = 0.7) +  
  geom_point(aes(x = ts_length,
                 y = Slope,
                 col = parameter),
             alpha = 0.7) +
  geom_smooth(method = "lm", se = TRUE,
              aes(x = ts_length,
                  y = Slope,
                  col = parameter),
              alpha = 0.6) +
  facet_wrap(~parameter, scales = "free") +
  theme(legend.position = "none") +
  labs(title = "Slopes as a function of time series length for each parameter",
       x = "Time Series length (years)",
       subtitle = "slopes are in [parameter's measurement units] / year")
```


```{r, fig.width = 6, fig.height = 3.5}
seas_met <- trends_all |>
  filter(type == "met") |> 
  summarize(.by = c(parameter, sig_seasonality),
            n()) |> 
  pivot_wider(names_from = sig_seasonality,
              values_from = `n()`) |> 
  mutate(no = -1*no)

ggplot(seas_met) +
  geom_segment( aes(x=parameter, xend=parameter, y=no, yend=yes)) +
  geom_point( aes(x=parameter, y=no, color="seasonal"), size=3 ) +
  geom_point( aes(x=parameter, y=yes, color="not seasonal"), size=3 ) +
  geom_hline(yintercept = 0) +
  scale_color_brewer(palette = "Set1") +
  coord_flip()+
  theme(
    legend.position = "none",
  ) +
  xlab("") +
  ylab("# of stations displaying seasonality")
```


## NUT  

```{r}
trends_all |>
  filter(type == "nut") |> 
  arrange(parameter, Slope, station) |> 
  mutate(stparm = paste0(station, parameter)) |> 
  ggplot(aes(x = forcats::fct_inorder(stparm), y = Slope)) +
  geom_pointrange(aes(ymin = conf.low, ymax = conf.high,
                      col = sig_trend)) +
  geom_hline(yintercept = 0) +
  facet_wrap(~parameter, scales = "free") +
  labs(title = "Slopes for all stations",
       subtitle = "slopes are in (log-10 [nutrient units]) / year",
       x = "Station",
       col = "Significant slope?") +
  theme(axis.text.x = element_blank(), 
        legend.text = element_text(size = 8),
        legend.title = element_text(size = 8),
        legend.position = "bottom", 
        legend.justification = "left",
        legend.direction = "horizontal")
```

```{r}
ggplot(filter(trends_all, type == "nut")) +
  geom_histogram(aes(x = Slope,
                     fill = parameter),
                 bins = 30,
                 col = "gray20",
                 alpha = 0.8) +
  facet_wrap(~parameter, scales = "free") +
  geom_vline(xintercept = 0,
             linewidth = 1) +
  theme(legend.position = "none") +
  labs(title = "Histograms of slopes for each parameter",
       subtitle = "slopes are in (log-10 [nutrient units]) / year")
```


```{r}
ggplot(filter(trends_all, type == "nut")) +
  geom_hline(yintercept = 0,
             linewidth = 0.7) +  
  geom_point(aes(x = ts_length,
                 y = Slope,
                 col = parameter),
             alpha = 0.7) +
  geom_smooth(method = "lm", se = TRUE,
              aes(x = ts_length,
                  y = Slope,
                  col = parameter),
              alpha = 0.6) +
  facet_wrap(~parameter, scales = "free") +
  theme(legend.position = "none") +
  labs(title = "Slopes as a function of time series length for each parameter",
       x = "Time Series length (years)",
       subtitle = "slopes are in log10[parameter's measurement units] / year")
```


```{r, fig.width = 6, fig.height = 3.5}
seas_nut <- trends_all |> 
  filter(type == "nut") |> 
  summarize(.by = c(parameter, sig_seasonality),
            n()) |> 
  pivot_wider(names_from = sig_seasonality,
              values_from = `n()`) |> 
  mutate(no = -1*no)

ggplot(seas_nut) +
  geom_segment( aes(x=parameter, xend=parameter, y=no, yend=yes)) +
  geom_point( aes(x=parameter, y=no, color="seasonal"), size=3 ) +
  geom_point( aes(x=parameter, y=yes, color="not seasonal"), size=3 ) +
  geom_hline(yintercept = 0) +
  scale_color_brewer(palette = "Set1") +
  coord_flip()+
  theme(
    legend.position = "none",
  ) +
  xlab("") +
  ylab("# of stations displaying seasonality")
```

# By parameter, including seasonal breakdowns  


```{r, results = "asis"}
for(i in seq_along(parms)){
    prm <- parms[i]
    cat("\n")
    cat("##", prm, "\n")
    tmp_overall <- filter(trends_all, parameter == parms[i])
    tmp_seas <- filter(trends_seasonal, parameter == parms[i])
    chld <- knitr::knit_child("trend_visualizations_child.Rmd", quiet = TRUE)
    cat(chld, sep = "\n")
}
```






