---
title: "Seasonal Box Plots"
output: html_document
date: "`r Sys.Date()`"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
source(here::here("helper_files", "definitions.R"))
source(here::here("helper_files", "functions.R"))
```

# WQ  

Go one region at a time?
```{r}
path <- here::here("Data_processing", "compiled_by_stn")
```


```{r}
for(rg in stns_in_regions$region){
  # get a vector of the stations
  stns <- unlist(stns_in_regions[stns_in_regions$region == rg & grepl("wq$", stns_in_regions$station_code), "station_code"])
  
  # read the data into a list and combine to data frame
  wq <- purrr::map(stns, function(x) get(load(paste0(path, "/", x, ".RData")))) %>% 
    purrr::set_names(stns) %>% 
    purrr::list_rbind(names_to = "stn") %>% 
    select(stn, datetimestamp, any_of(params_wq), any_of(f_wq))
  
  # QAQC
  wq2 <- qaqc_df(wq, params_wq, type = "wq")

}
```

```{r}
# test <- wq[sample(1:nrow(wq), size = 1000), ]

# run qaqc on the data frame
wq2 <- qaqc_df(wq, params_wq, type = "wq")


# get median of each param by year-month combo, then by months across years
wq3 <- wq2 %>% 
  mutate(Year = lubridate::year(datetimestamp),
         Month = lubridate::month(datetimestamp)) %>% 
  group_by(stn, Year, Month) %>% 
  summarize(across(all_of(params_wq), function(x) median(x, na.rm = TRUE))) %>% 
  mutate(reserve = substr(stn, 1, 3))
```

```{r}
  ggplot(wq3, aes(x = factor(Month), y = sal, group = Month)) +
    geom_boxplot() +
    facet_wrap(~ stn, ncol = 4)

```

