---
title: ""
output: html_document
---



```{r}
fparm <- paste0("f_", parm)
```

```{r}
# make a subset of the data frame, with consistent names for easier graphing  
# will refer back to parm variable in titles etc  

dat_sub <- dat[ , c("datetimestamp", parm, fparm)]
names(dat_sub) <- c("datetimestamp", "value", "flagCode")


# extract information from the flag/code column
dat_sub <- dat_sub %>% 
  mutate(Year = lubridate::year(datetimestamp),
         Month = lubridate::month(datetimestamp),
         Day = lubridate::mday(datetimestamp),
         flag = extract_flag(flagCode),
         keepStatus = case_when(flag %in% flags_keep ~ "keep",
                                .default = "discard"))

# daily and monthly summaries  
dails <- dat_sub %>% 
  group_by(Year, Month, Day) %>% 
  summarize(keptDataPoints = sum(keepStatus == "keep"))

monts <- dails %>% 
  group_by(Year, Month) %>% 
  summarize(useableDays = sum(keptDataPoints > 0),
            badDays = sum(keptDataPoints == 0)) %>% 
  mutate(YearMonth = as.Date(paste(Year, Month, "01", sep = "-")),
         YearMonthText = str_sub(as.character(YearMonth), end = -4))
```

### Plot  

```{r}
# number of bad days by month
p <- ggplot(monts, aes(x = YearMonth, y = badDays,
                  fill = as.factor(Year),
                  tooltip = paste0(YearMonthText, ":\n n = ", badDays))) +
  geom_col_interactive() +
  theme_bw() +
  labs(title = paste(st, parm),
       subtitle = "Days in month with no useable data points",
       fill = "Year")

ggiraph::girafe(ggobj = p)
```

```{r}
# number of good days by month

p <- ggplot(monts, aes(x = YearMonth, y = useableDays,
                  fill = as.factor(Year),
                  tooltip = paste0(YearMonthText, ":\n n = ", useableDays))) +
  geom_col_interactive() +
  theme_bw() +
  labs(title = paste(st, parm),
       subtitle = "Days in month with >= 1 useable data point",
       fill = "Year")

ggiraph::girafe(ggobj = p)
```




