---
title: "Exploration of Predictor Variables"
output: 
  html_document:
    toc: true
    toc_float: true
date: "`r Sys.Date()`"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      message = FALSE,
                      warning = FALSE)

# packages
library(tidyverse)
library(NADA2)  # for cfit - Kaplan Meier estimation
library(GGally) # for ggpairs
library(corrplot) # for corrplot


# parameters and columns to keep
params_wq <- c("temp_median", "spcond_median", 
               "turb_median")
params_nut <- c("chla_n", "chla_n_cens",
                "nh4f", "nh4f_cens",
                "no23f", "no23f_cens",
                "po4f", "po4f_cens")
params_met <- c("atemp_median", "wspd_median",
                "maxwspd_median", "totprcp_total",
                "dailyPAR_median")
params_trends <- c("temp_median", "spcond_median", "turb_median",
                   "chla_n", "po4f", "nh4f", "no23f",
                   "atemp_median", "dailyPAR_median",
                   "sqrt_precp_total")
```

Need to bring everything together: slopes and long-term medians.  

# Data import  

Read in wq, met, nut data. Only keep key parameters (and medians). Calculate long-term medians for every monthly median. Use Kaplan-Meier methods on censored data (NUT). Bind WQ and NUT stations. Find primary SWMP MET station for each reserve and bind to the wq/nut stations on reserve.  

```{r load-data}
load(here::here("Data", "QAQCd_monthly_byType", "SWMP_monthlyWQ.RData"))
load(here::here("Data", "QAQCd_monthly_byType", "SWMP_monthlyNUT.RData"))  
load(here::here("Data", "QAQCd_monthly_byType", "SWMP_monthlyMET.RData")) 

load(here::here("Outputs", "calculated_trends", "long-term-trends.RData"))
load(here::here("Outputs", "calculated_trends", "seasonal_characterization.RData"))
```


```{r select-filter-data}
wq <- wq |> 
  mutate(reserve = substr(station, start = 1, stop = 3),
         station = substr(station, start = 1, stop = 5)) |> 
  select(reserve, station, 
         year, month,
         all_of(params_wq))

nut <- nut |> 
  mutate(reserve = substr(station, start = 1, stop = 3),
         station = substr(station, start = 1, stop = 5)) |> 
  select(reserve, station, 
         year, month,
         all_of(params_nut))  

met <- met |> 
  mutate(reserve = substr(station, start = 1, stop = 3)) |> 
  select(reserve, station, 
         year, month,
         all_of(params_met))

trnds <- bind_rows(trends_df, trends_met, trends_nut) |> 
  mutate(reserve = substr(station, start = 1, stop = 3),
         station = substr(station, start = 1, stop = 5)) |> 
  filter(parameter %in% params_trends) |> 
  select(reserve, station, parameter, Slope)
```


```{r calc-medians}
wq_medians <- wq |> 
  summarize(.by = c(reserve, station),
            across(temp_median:turb_median, function(x) median(x, na.rm = TRUE)))

met_medians <- met |> 
  summarize(.by = c(reserve, station),
            across(atemp_median:dailyPAR_median, function(x) median(x, na.rm = TRUE)))


extract_cens_median <- function(df, nut, nut_cens){

  # nut and nut_cens should be entered as character strings
  
  tmp <- df[c(nut, nut_cens)]
  names(tmp) <- c("nut", "nut_cens")

  station <- unique(df$station)
  param <- nut
    
  tmp <- tmp |> 
    na.omit() |> 
    mutate(nut = case_when(nut <=0 ~ 0.0001,
                           .default = nut)) 
  
  if(nrow(tmp) < 5) return(list(station = station,
                                param = param,
                                KMmedian = NA,
                                PctND = NA))
  if(sum(tmp$nut_cens == 0) < 2) return(list(station = station,
                                param = param,
                                KMmedian = NA,
                                PctND = NA))
  
  tmp_fit <- cfit(tmp$nut, tmp$nut_cens, Cdf = FALSE, printstat = FALSE)
  KMmedian <- tmp_fit$KMmedian
  
  KMmedian <- ifelse(is.character(KMmedian),
                     as.numeric(str_remove(KMmedian, "<")),
                     KMmedian)
  
  PctND <- tmp_fit$PctND
  
  return(list(station = station,
              param = param,
              KMmedian = KMmedian,
              PctND = PctND))
}

nut_values <- c("chla_n", "nh4f", "no23f", "po4f")
nut_censoreds <- paste0(nut_values, "_cens")

nut_split <- nut |> 
  split(nut$station)

nut_KMs <- map(nut_split, 
               function(X) map2(nut_values, nut_censoreds,
                                ~extract_cens_median(X, .x, .y )) ) |> 
  bind_rows()

nut_medians <- nut_KMs |> 
  select(station, param, KMmedian) |>
  pivot_wider(id_cols = station,
              names_from = param,
              names_glue = "{param}_median",
              values_from = KMmedian) |> 
  mutate(reserve = substr(station, start = 1, stop = 3)) |> 
  relocate(reserve)
```

```{r join-water-params}
water_medians <- left_join(wq_medians, nut_medians,
                           by = c("reserve", "station"))
```

```{r}
Q <- cor(water_medians[3:ncol(water_medians)], 
         method = "spearman",
         use = "pairwise.complete.obs")
testRes2 = cor.mtest(water_medians[3:ncol(water_medians)], conf.level = 0.95)


corrplot(Q, 
         type = "upper",
         order = 'AOE',
         method = "ellipse",
         p.mat = testRes2$p, 
         sig.level = 0.05,
         addCoef.col = "gray20",
         insig = "blank",
         tl.pos = "lt",
         tl.cex = 0.8,
         tl.srt = 45,
         title = "Ellipses only for significant corrs; numbers for all")
corrplot(Q, add = TRUE,
         type = "lower",
         order = 'AOE',
         method = "number",
         p.mat = testRes2$p, 
         sig.level = 0.05,
         insig = "label_sig",
         pch.cex = 2.5,
         pch.col = "gray40",
         diag = FALSE,
         tl.pos = "n",
         cl.pos = "n")

```







```{r}
wq_medians |> 
  select(-reserve, -station) |> 
  ggpairs(upper = list(continuous = wrap("cor", method = "spearman")),
          lower = list(continuous = wrap("smooth", method = "loess", col = "blue", alpha = 0.4))) +
  labs(title = "Spearman correlation coefficients of long-term WQ medians")


pairs(wq_medians[, 3:ncol(wq_medians)],
      lower.panel = panel.smooth,
      upper.panel = "cor")


lowerFn <- function(data, mapping, method = "lm", ...) {
  p <- ggplot(data = data, mapping = mapping) +
    geom_point(colour = "blue", alpha = 0.5) +
    geom_smooth(method = method, color = "red", 
                se = FALSE, linewidth = 0.8, ...)
  p
}

wq_medians |> 
  select(-reserve, -station) |> 
  ggpairs(upper = list(continuous = wrap("cor", method = "spearman")),
          lower = list(continuous = wrap(lowerFn))) +
  labs(title = "Pairs Plots with Spearman Correlation Coefficients")
```



```{r}
Q <- cor(wq_medians[3:ncol(wq_medians)], method = "spearman")
testRes2 = cor.mtest(wq_medians[3:ncol(wq_medians)], conf.level = 0.95)


corrplot(Q, 
         type = "upper",
         order = 'AOE',
         method = "ellipse",
         p.mat = testRes2$p, 
         sig.level = 0.05,
         tl.pos = "lt",
         tl.srt = 45,
         insig = "blank",
         addCoef.col = "gray20")
corrplot(Q, add = TRUE,
         type = "lower",
         order = 'AOE',
         method = "number",
         p.mat = testRes2$p, 
         sig.level = 0.05,
         tl.pos = "n",
         cl.pos = "n",
         diag = FALSE,
         insig = "blank")


```

