---
title: "Adding info from SWMP CLUE and VIMS Clustering to compiled predictors"
date: today
format: 
    html:
        toc: true
        toc-location: left
        code-fold: true
        embed-resources: true
warning: false
message: false
error: true
---

```{r}
library(tidyverse)
library(readxl)
```

# Set up import and export paths  

```{r}
# compiled data frames, in and out
comp_in <- here::here("Outputs", "04_compiled_predictors",
                      "compiled_predictors_MDL.csv")

comp_out <- here::here("Outputs", "04_compiled_predictors",
                      "compiled_predictors_withExternalInfo_MDL.csv")

# external info to import
clue_in <- here::here("Data", "SWMP CLUE_All Site Classification_June2024_wLatLon.xlsx")

clusters_in <- here::here("Outputs", "01b_median-clustering-DP-CF",
                          "swmp_clstr_med_pc.csv")
```

# Import and prep external info  

Trim station names; when Ecoregion isn't present insert NERR_Bioregion (Great Lakes sites), subset  

```{r}
clue <- read_xlsx(clue_in)
clue2 <- clue |> 
  mutate(StationCode = tolower(StationCode),
         StationCode = substr(StationCode, 1, 5),
         Ecoregion = case_when(is.na(Ecoregion) ~ NERR_BioRegion,
                               .default = Ecoregion)) |> 
  select(station = StationCode,
         StationName,
         Ecoregion:PrimaryWaterSource,
         BioticSetting:BioticSubclass,
         Dev_TotalArea:Imp_pctLand
         )
```


```{r}
clusters <- read.csv(clusters_in) |> 
  select(station = code,
         cluster)
```



# Import compiled data frames and join  

```{r}
comp <- read.csv(comp_in)

comp_joined <- comp |> 
  left_join(clue2, by = "station") |> 
  left_join(clusters, by = "station")

```


# Export  

```{r}
write.csv(comp_joined,
          comp_out,
          na = "",
          row.names = FALSE)
```


